name: recook
description: Aplikasi buku resep digital untuk memasak mudah.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  dio: ^5.3.3
  provider: ^6.0.5 
  sqflite: ^2.3.0
  url_launcher: ^6.2.1

dev_dependencies:

  build_runner: ^2.0.7

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ 
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
